import React from 'react'
import { NavLink } from 'react-router-dom'

export default function FooterBottom() {
    return (
        <>
            
                <footer className='pt-5 footer-bottom'>
                    <div className='container'>
                    <div className='row'>
                        <div className='col-lg-3'>
                            <h3 className='footer-header'>How Daraz Transformed Online Shopping in Pakistan</h3>
                            <p>Daraz first made waves in Pakistan’s e-commerce market after its introduction in 2012. We have since grown to become Pakistan’s largest platform for online shopping with a network spread across Asia in Pakistan, Bangladesh, Sri Lanka, Myanmar, and Daraz.com.np. Our vision was to provide a safe, efficient online marketplace platform for vendors and customers across the country to come together. We started off exclusively as an online fashion retail platform and over the years expanded to become a complete one-stop solution for all your buying needs. Daraz prides itself on not being just another ecommerce venture in Asia. We work tirelessly to make sure that we provide users with the best online online shopping experience and value for their purchases. Whether you shop online through our website or our online shopping mobile App, you can expect easy navigation, customized recommendations, and a smooth online shopping experience guaranteed.</p>
                            <b className='footer-header mt-3'>What Makes Us Different from Other Online Shopping Platforms?</b>
                            <b>Select from the Largest Online Marketplace in Pakistan</b><p>
                                With over 15 million products to select from, Daraz offers its customers the most comprehensive listing of products in the country. Whether you’re looking for electronics, apparel, appliances, or groceries – there is something for everyone.</p>
                            <b>Hassle Free Delivery</b><p>
                                Online shopping is only as good as its execution and Daraz promises hassle free delivery right from the moment you order to when your package is dropped at your door. We cater to both major and smaller cities alike, and give you the choice to track your package as it makes its way to you so you always know your order status. If you are unsatisfied with any aspect of your order, we have a simple 7-day return or exchange policy.</p>
                            <b>Payment Options to Suit Every Style</b><p>
                                You can choose to pay through a credit/debit card, opt for cash on delivery or even go for EMI (easy monthly instalments). You can also avail exclusive offers by downloading Daraz Wallet – a closed loop digital wallet that offers you a secure, easy way to make payments. We also have easypaisa & jazzcash payment method for our customers' ease
                            </p>

                        </div>
                        <div className='col-lg-3'>
                            <b>Shop from Verified Vendors</b>
                            <p>Daraz understands that online shopping in Pakistan comes with its fair share of risks. This is why with Daraz Marketplace and Daraz Mall customers have the security of choosing from verified vendors and brands from Karachi, Lahore, Islamabad and all across Pakistan. Now you’ll never have to second guess authenticity because Daraz makes sure to do it for you!</p>
                            <b>Shop Around the World with Daraz Global Collection</b>
                            <p>International sellers and local convenience come together with Daraz Global collection. Get the chance to shop online from vendors around the world without leaving the Daraz website. Featuring thousands of novelty gadgets and accessories, Daraz Global Collection offers you a selection of products that you won’t find anywhere else when you’re online shopping in Pakistan.</p>
                            <b>Avail Exclusive Discounts, Offers, and Promotions</b>
                            <p>Online shopping with Daraz means you get the chance to avail exclusive online-only promotional packages as well as discount vouchers from our vendors when you shop from their pages. Our flash sales give you customized product offers all curated with the help of our advanced AI technology so you always have deals you’ll actually be interested in!</p>
                            <b>Buy Value, not Just Goods with Daraz Care</b>
                            <p>Daraz does not just cater online shopping in Pakistan but also aims to simplify the way you give back to society. With charities spanning across sectors of education, health care, environmental preservation, and shelters, you can choose to make a big difference with a few, simple clicks.</p>
                            <b>Simplify Corporate Purchases</b>
                            <p>Who says corporate purchases need to be a complicated affair? When you opt for Daraz Corporate, you get an efficient and transparent solution for your business’ bulk purchasing needs. We’re proud to be working with some of the most prestigious organizations in Pakistan across a number of different industries.</p>
                        </div>
                        <div className='col-lg-3 under-line'>
                            
                            <h3 className='footer-header'>Top Categories & Brands</h3>
                            <NavLink className="nav-line"><b>MOBILE PHONES IN PAKISTAN</b></NavLink>
                            <p><NavLink className="nav-line">Apple iPhones</NavLink>,<NavLink className="nav-line"> Honor Mobiles</NavLink>,<NavLink className="nav-line"> Huawei Mobiles</NavLink>, <NavLink className="nav-line">Tecno Mobiles</NavLink>,<NavLink className="nav-line"> Redmi Mobiles</NavLink>,<NavLink className="nav-line"> Xiaomi Mi Mobiles</NavLink>,<NavLink className="nav-line"> Nokia Mobiles</NavLink>, <NavLink className="nav-line">OnePlus Mobiles</NavLink>,<NavLink className="nav-line"> Oppo Mobile Phones</NavLink>,<NavLink className="nav-line"> Realme Mobiles</NavLink>,<NavLink className="nav-line"> Samsung Mobile Phones</NavLink>,<NavLink className="nav-line"> Vivo Mobile Phones</NavLink>, <NavLink className="nav-line">Mobile Accessories</NavLink>, <NavLink className="nav-line">Smart Watches</NavLink></p>
                            <NavLink className="nav-line"><b>LATEST LAPTOPS</b></NavLink>
                            <p><NavLink className="nav-line">Dell Laptops</NavLink>,<NavLink className="nav-line"> HP Laptops</NavLink>,<NavLink className="nav-line"> Lenovo Laptops</NavLink>,<NavLink className="nav-line"> Mouse</NavLink>,<NavLink className="nav-line"> Gaming Graphic Cards</NavLink>,<NavLink className="nav-line"> lenovo ideapad 3</NavLink>, <NavLink className="nav-line">Macbook Pro 13</NavLink>,<NavLink className="nav-line"> Hp Probook 650 G2</NavLink></p>
                            <NavLink className="nav-line"><b>LED TV</b></NavLink>
                            <p><NavLink className="nav-line">Changhong Led Tv</NavLink>,<NavLink className="nav-line"> LG Led Tv</NavLink>,<NavLink className="nav-line"> Samsung Led Tv</NavLink>, <NavLink className="nav-line">Sony Led Tv</NavLink>,<NavLink className="nav-line"> TCL LED TVs</NavLink></p>
                            <NavLink className="nav-line"><b>HOME APPLIANCES</b></NavLink>
                            <p><NavLink className="nav-line">Microwave oven</NavLink>,<NavLink className="nav-line"> Geyser, Heater</NavLink>, <NavLink className="nav-line">Refrigerators</NavLink>,<NavLink className="nav-line"> Deep Freezers</NavLink>, <NavLink className="nav-line">Generators</NavLink>, <NavLink className="nav-line">Water Dispensers</NavLink>, <NavLink className="nav-line">Fans, Room Cooler</NavLink>, <NavLink className="nav-line">Table Fans</NavLink>, <NavLink className="nav-line">Wall Fans</NavLink>,<NavLink className="nav-line"> Exhaust Fans</NavLink>,<NavLink className="nav-line"> Pedestal Fans</NavLink>,<NavLink className="nav-line"> Window Ac</NavLink>, <NavLink className="nav-line">Solar Panel</NavLink>,<NavLink className="nav-line"> Washing Machine</NavLink></p>


                            <NavLink className="nav-line"><b>DSLR CAMERAS</b></NavLink>
                            <p><NavLink className="nav-line">Camera Tripods</NavLink>,<NavLink className="nav-line"> Drones, IP & CCTV Cameras</NavLink>,<NavLink className="nav-line"> Nikon D7000</NavLink>,<NavLink className="nav-line"> Nikon D5600</NavLink>, <NavLink className="nav-line">Canon 200D</NavLink>, <NavLink className="nav-line">Canon 1200D</NavLink>,<NavLink className="nav-line"> Fujifilm Instax Mini 11</NavLink>, <NavLink className="nav-line">Canon M50</NavLink></p>
                            <NavLink className="nav-line"><b>HEALTH & BEAUTY</b></NavLink>
                            <p><NavLink className="nav-line">sunisa foundation</NavLink>,<NavLink className="nav-line"> Biofad, janssen facial kit</NavLink>,<NavLink className="nav-line"> Glutathione Injection</NavLink>,<NavLink className="nav-line"> Glutathione Cream Sauvage</NavLink>,<NavLink className="nav-line"> Glutathione Tablets</NavLink>,<NavLink className="nav-line"> Glutathione Soap</NavLink>,<NavLink className="nav-line"> Infrared Thermometers</NavLink>,<NavLink className="nav-line"> N95 Mask</NavLink></p>
                            <NavLink className="nav-line"><b>TRENDING</b></NavLink>
                            <p><NavLink className="nav-line">June Shopping Expo 2023</NavLink>, <NavLink className="nav-line">Azaadi Sale 2022</NavLink>,<NavLink className="nav-line"> Shopping Expo</NavLink>, <NavLink className="nav-line">11 11 Sale</NavLink>, <NavLink className="nav-line">12.12 Sale</NavLink>,<NavLink className="nav-line"> Live Cricket Streaming</NavLink>, <NavLink className="nav-line">Online Bills</NavLink>, <NavLink className="nav-line">Core I5 Laptop</NavLink>, <NavLink className="nav-line">Gtx 1060</NavLink>,<NavLink className="nav-line"> Samsung A32</NavLink>,<NavLink className="nav-line"> Samsung A51</NavLink>,<NavLink className="nav-line"> Samsung A52</NavLink>,<NavLink className="nav-line"> Samsung A71</NavLink>, <NavLink className="nav-line">Samsung A72</NavLink>, <NavLink className="nav-line">Samsung M31</NavLink>, <NavLink className="nav-line">amsung S20</NavLink>,<NavLink className="nav-line"> Samsung S20 Ultra 5G</NavLink>,<NavLink className="nav-line"> Samsung S21</NavLink>, <NavLink className="nav-line">Samsung S21 Ultra</NavLink>,<NavLink className="nav-line"> Samsung Z Flip</NavLink>,<NavLink className="nav-line"> Tecno Camon 17</NavLink>,<NavLink className="nav-line"> Tecno Spark 6</NavLink>, <NavLink className="nav-line">Vivo V20</NavLink>, <NavLink className="nav-line">Poco X3 Pro</NavLink>,<NavLink className="nav-line"> Vivo V21</NavLink>,<NavLink className="nav-line"> Vivo V21E</NavLink>,<NavLink className="nav-line"> Vivo X70 Pro</NavLink>,<NavLink className="nav-line"> Vivo Y12</NavLink>, <NavLink className="nav-line">Vivo Y12S</NavLink>,<NavLink className="nav-line"> Vivo Y1S</NavLink>,<NavLink className="nav-line"> Vivo Y20</NavLink>,<NavLink className="nav-line"> Vivo Y51</NavLink>,<NavLink className="nav-line"> Vivo Y51S</NavLink>,<NavLink className="nav-line"> Oppo F19 Pro</NavLink>,<NavLink className="nav-line"> Oppo Reno 6</NavLink>,<NavLink className="nav-line"> Xiaomi Poco F3</NavLink>,<NavLink className="nav-line"> Xiaomi Poco M3</NavLink>,<NavLink className="nav-line"> Xiaomi Poco X3</NavLink>, <NavLink className="nav-line">Xiaomi Poco X3 Gt</NavLink>,<NavLink className="nav-line"> Xiaomi Redmi 9C</NavLink>,<NavLink className="nav-line"> Xiaomi Redmi Note 10 Pro</NavLink>, <NavLink className="nav-line">Sharp Aquos R2</NavLink></p>
                            <NavLink className="nav-line"><b>SHOP WORLDWIDE WITH LAZADA</b></NavLink>
                            <p><NavLink className="nav-line">Singapore</NavLink>, <NavLink className="nav-line">Malaysia</NavLink>,<NavLink className="nav-line"> Philipines</NavLink>, <NavLink className="nav-line">Indonesia</NavLink>,<NavLink className="nav-line"> Vietnam</NavLink>,<NavLink className="nav-line"> Thailand</NavLink></p>
                             
                        </div>
                        <div className='col-lg-3 under-line'>
                            <NavLink className="nav-line">
                            <b>WOMEN'S FASHION</b></NavLink>
                            <p><NavLink className="nav-line">Al-Karam Studio</NavLink>,<NavLink className="nav-line"> Warda, Salitex</NavLink>,<NavLink className="nav-line"> Bonanza Satrangi</NavLink>, <NavLink className="nav-line">Edenrobe</NavLink>, <NavLink className="nav-line">Firdous</NavLink>, <NavLink className="nav-line">Junaid Jamshed</NavLink>, <NavLink className="nav-line">Limelight</NavLink>,<NavLink className="nav-line"> Sana Safinaz</NavLink>, <NavLink className="nav-line">Mahru, Pushup Bra</NavLink>,<NavLink className="nav-line"> Women Undergarments</NavLink></p>
                            <NavLink className="nav-line"><b>MEN'S FASHION</b></NavLink>
                            <p><NavLink className="nav-line">Men's Shirts</NavLink>,<NavLink className="nav-line"> Men's T-Shirts</NavLink></p>
                            <NavLink className="nav-line"><b>ONLINE GROCERY STORE</b></NavLink>
                            <p><NavLink className="nav-line">Oil & Ghee</NavLink>,<NavLink className="nav-line"> Basmati Rice</NavLink>,<NavLink className="nav-line"> Dried Fruits</NavLink>,<NavLink className="nav-line"> Chocolates</NavLink>,<NavLink className="nav-line"> Mattresses</NavLink></p>
                            <NavLink className="nav-line"><b>ONLINE BOOK STORE</b></NavLink>
                            <p><NavLink className="nav-line">English Books</NavLink>,<NavLink className="nav-line"> Islamic Books</NavLink>,<NavLink className="nav-line"> History Books</NavLink>,<NavLink className="nav-line"> English Literature Books</NavLink>,<NavLink className="nav-line"> Kids Urdu Stories</NavLink>, <NavLink className="nav-line">Pride & Prejudice</NavLink>, <NavLink className="nav-line">Harry Potter Story Books</NavLink>,<NavLink className="nav-line"> Namal Novel</NavLink>, <NavLink className="nav-line">Nimra Ahmed Novels</NavLink></p>
                            <NavLink className="nav-line"><b>USED CARS FOR SALE</b></NavLink>
                            <p><NavLink className="nav-line">Suzuki Wagon R</NavLink>,<NavLink className="nav-line"> KIA Sportage</NavLink>,<NavLink className="nav-line"> Honda City</NavLink>, <NavLink className="nav-line">Toyota Prado</NavLink>,<NavLink className="nav-line"> Suzuki Alto</NavLink>,<NavLink className="nav-line"> Suzuki Cultus</NavLink>,<NavLink className="nav-line"> Honda Civic</NavLink>,<NavLink className="nav-line"> Honda 125</NavLink>, <NavLink className="nav-line">Honda 70</NavLink>,<NavLink className="nav-line"> Yamaha Ybr 125</NavLink>,<NavLink className="nav-line"> Hi Speed 150</NavLink>,<NavLink className="nav-line"> Hi Speed Freedom 200</NavLink>,<NavLink className="nav-line"> Metro 70</NavLink>,<NavLink className="nav-line"> Super Power 125</NavLink>,<NavLink className="nav-line"> Monster JMS 3500 Electric Bike</NavLink>,<NavLink className="nav-line"> Super Power 70</NavLink>,<NavLink className="nav-line"> Car Accessories</NavLink></p>
                            <NavLink className="nav-line"><b>AIR CONDITIONERS</b></NavLink>
                            <p><NavLink className="nav-line">Kenwood Ac</NavLink>,<NavLink className="nav-line"> Haier Ac</NavLink>,<NavLink className="nav-line"> Gree Ac</NavLink>,<NavLink className="nav-line"> Dawlance Ac</NavLink>,<NavLink className="nav-line"> Orient Ac</NavLink>,<NavLink className="nav-line"> Ecostar Ac</NavLink>,<NavLink className="nav-line"> Inverex Solar Ac</NavLink>,<NavLink className="nav-line"> Pel Ac</NavLink></p>
                            <NavLink className="nav-line"><b>TOP MOBILE PHONES</b></NavLink>
                            <p><NavLink className="nav-line">Nokia G20</NavLink>,<NavLink className="nav-line"> redmi 9</NavLink>,<NavLink className="nav-line"> realme 7 pro</NavLink>, <NavLink className="nav-line">realme c15</NavLink>,<NavLink className="nav-line"> realme c21</NavLink>,<NavLink className="nav-line"> vivo y20s</NavLink>,<NavLink className="nav-line"> realme c11 Price in Pakistan</NavLink>,<NavLink className="nav-line"> itel vision 1 pro price in pakistan</NavLink>,<NavLink className="nav-line"> samsung galaxy a02 price in pakistan</NavLink>,<NavLink className="nav-line"> Infinix Hot 10</NavLink>,<NavLink className="nav-line"> Infinix Hot 8</NavLink>,<NavLink className="nav-line"> Infinix Hot 9</NavLink>,<NavLink className="nav-line"> Infinix Note 10 Pro</NavLink>,<NavLink className="nav-line"> Infinix Note 7</NavLink>, <NavLink className="nav-line">Infinix Note 8</NavLink>,<NavLink className="nav-line"> Infinix Zero 8</NavLink>,<NavLink className="nav-line"> Inifnix Smart 5</NavLink>, <NavLink className="nav-line">iPhone 11</NavLink>,<NavLink className="nav-line"> iPhone 12</NavLink>,<NavLink className="nav-line"> iphone 12 Pro Max</NavLink>,<NavLink className="nav-line"> iPhone 12 Pro</NavLink>,<NavLink className="nav-line"> iPhone 6</NavLink>,<NavLink className="nav-line"> Itel A25</NavLink>,<NavLink className="nav-line"> Mi 10T</NavLink>,<NavLink className="nav-line"> Nokia 105</NavLink>,<NavLink className="nav-line"> Oppo A15</NavLink>,<NavLink className="nav-line"> Oppo A15S</NavLink>,<NavLink className="nav-line"> Oppo A53</NavLink>,<NavLink className="nav-line"> Oppo A54</NavLink>,<NavLink className="nav-line"> Infinix Zero X Pro</NavLink>, <NavLink className="nav-line">Infinix Zero X Neo</NavLink>,<NavLink className="nav-line"> Oppo F19</NavLink>, <NavLink className="nav-line">Oppo Reno 5</NavLink>,<NavLink className="nav-line"> Oppo Reno 5 Pro</NavLink>,<NavLink className="nav-line"> Xiaomi Poco M3 Pro</NavLink>,<NavLink className="nav-line"> Realme 6 Pro</NavLink>,<NavLink className="nav-line"> Realme 8</NavLink>,<NavLink className="nav-line"> Realme Narzo 30A</NavLink>,<NavLink className="nav-line"> Samsung A02S</NavLink>,<NavLink className="nav-line"> Samsung A11</NavLink>, <NavLink className="nav-line">Samsung A12</NavLink>,<NavLink className="nav-line"> Samsung A31</NavLink>, <NavLink className="nav-line">Vivo Y33s</NavLink>,<NavLink className="nav-line"> Infinix Note 11</NavLink>, <NavLink className="nav-line">Tecno Spark 6 Go</NavLink>,
                            <NavLink className="nav-line"> Samsung A52s</NavLink>,<NavLink className="nav-line"> Samsung Tab A7 Lite</NavLink>,
                            <NavLink className="nav-line"> Oppo Reno 6 Pro</NavLink></p>
                            <NavLink className="nav-line"><b>MEDICINE</b></NavLink>
                            <p><NavLink className="nav-line">surbex z</NavLink>,<NavLink className="nav-line"> tea tree oil</NavLink>,<NavLink className="nav-line"> hydrozole cream</NavLink>,<NavLink className="nav-line"> biotin tablets</NavLink>,<NavLink className="nav-line"> evion capsule</NavLink>,<NavLink className="nav-line"> lactogen 1</NavLink>,<NavLink className="nav-line"> minoxidil</NavLink>, <NavLink className="nav-line">clobevate cream</NavLink>, <NavLink className="nav-line">centrum silver</NavLink>,<NavLink className="nav-line"> maxdif cream</NavLink>,<NavLink className="nav-line"> dermovate cream</NavLink>, <NavLink className="nav-line">cac 1000</NavLink>,<NavLink className="nav-line"> Panadol Migraine</NavLink></p>
                           
                        </div>
                    </div>
                    </div>
                </footer>
            
        </>
    )
}
